apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <h1>Gagan....Welcome to our Kubernetes website</h1>
        <p>This page is provided by a ConfigMap as a Test.</p>
      </body>
    </html>
