apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: stateful-demo
  namespace: project1-website

spec:
  serviceName: stateful-demo
  replicas: 3

  selector:
    matchLabels:
      app: stateful-demo

  template:
    metadata:
      labels:
        app: stateful-demo

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: project1-hostpath

        resources:
          requests:
            storage: 1Gi
